### ISSUE TITLE
Package not working within 64 bits python environnement

### ISSUE THREAD

**Issue by jmlaporte** [Esri/hermes#3]
Within 64 bits python environnement the package is not working. 

Especially, it is not possible to use it in a python script of an ArcGIS toolbox executed in Background (i.e. executed with python 64bits and background processing 64 bits).

**Comment by achapkowski** [comment]
@jmlaporte known issue.

**Comment by jmlaporte** [comment]
OK but is it planed to correct this issue ? and at which horizon ?
Thanks a lot to inform me.

**Comment by jmlaporte** [comment]
Do you have any idea about the provision of a new version able to execute like a background process  (within 64 bits environment) ?

Regards,

Jean-Michel

**Comment by achapkowski** [comment]
I do not know about porting to py2 x64 ArcMap.
